import { PLANE_CATEGORY, type loa } from "../types";

const loas: loa[] = [
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sea"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..RBL..LMT..HAWKZ"],
    is_rnav: true,
    notes: "FROM ZOA 36/41",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sea"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..BTG.OLM"],
    is_rnav: false,
    notes: "FROM ZOA 36/41",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["pdx"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..MACHU..TMBRS"],
    is_rnav: true,
    notes: "FROM ZOA 36/41",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["pdx"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..OED.OCITY"],
    is_rnav: false,
    notes: "FROM ZOA 36/41 or ZOA 41/44",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sea"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..LKV.HAWKZ", "..LMT..BTG..KRIEG.HAWKZ"],
    is_rnav: true,
    notes: "FROM ZOA 41/44",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["pdx"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..PORTL..TMBRS"],
    is_rnav: true,
    notes: "FROM ZOA 41/44",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["pdx"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..LMT.OCITY"],
    is_rnav: false,
    notes: "FROM ZOA 41/44",
  },
  //////////////////////////////////////
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sfo"],
    arr_flows: ["sfow"],
    plane_classifications: [PLANE_CATEGORY.JET, PLANE_CATEGORY.TURBOPROP],
    route: ["..MLBEC.BDEGA"],
    is_rnav: true,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sfo"],
    arr_flows: ["sfow"],
    plane_classifications: [PLANE_CATEGORY.JET, PLANE_CATEGORY.TURBOPROP],
    route: ["..RBG..PYE..SFO", "..RBL..PYE..SFO"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sfo"],
    arr_flows: ["sfow"],
    plane_classifications: [PLANE_CATEGORY.PROP],
    route: ["..ENI.PYE"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["oak"],
    arr_flows: ["sfow"],
    plane_classifications: [],
    route: ["..SPAMY.WNDSR"],
    is_rnav: true,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["oak"],
    arr_flows: ["sfow", "sfoe"],
    plane_classifications: [],
    route: ["..RBG..REBAS..OAK", "..RBL..REBAS..OAK"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sjc"],
    arr_flows: ["sfow"],
    plane_classifications: [PLANE_CATEGORY.JET, PLANE_CATEGORY.TURBOPROP],
    route: ["..CHBLI..BRIXX"],
    is_rnav: true,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sjc"],
    arr_flows: ["sfow"],
    plane_classifications: [PLANE_CATEGORY.JET, PLANE_CATEGORY.TURBOPROP],
    route: ["..RBG..PYE..SFO"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sjc"],
    arr_flows: ["sfow"],
    plane_classifications: [PLANE_CATEGORY.PROP],
    route: ["..ENI.PYE"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["smf"],
    arr_flows: ["smfs", "smfn"],
    plane_classifications: [],
    route: ["..LKV.TUDOR"],
    is_rnav: false,
    notes: "FROM ZSE 13",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["rno"],
    arr_flows: ["rnos"],
    plane_classifications: [],
    route: ["..HARTT.HARTT"],
    is_rnav: true,
    notes: "FROM ZSE 13",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["rno"],
    arr_flows: ["rnos", "rnon"],
    plane_classifications: [],
    route: ["..J5.FMG", "..J92.FMG"],
    is_rnav: false,
    notes: "FROM ZSE 13",
  },
  ///////////////////////////////////////////////////////////////
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sfo"],
    arr_flows: ["sfoe"],
    plane_classifications: [],
    route: ["..MLBEC.STLER"],
    is_rnav: true,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sfo"],
    arr_flows: ["sfoe"],
    plane_classifications: [],
    route: ["..RBG..STINS", "..RBL..STINS"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["oak"],
    arr_flows: ["sfoe"],
    plane_classifications: [],
    route: ["..SPAMY.AANET"],
    is_rnav: true,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sjc"],
    arr_flows: ["sfoe"],
    plane_classifications: [],
    route: ["..GGULF.FRLON"],
    is_rnav: true,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sjc"],
    arr_flows: ["sfoe"],
    plane_classifications: [],
    route: ["..RBG..BRINY", "..RBL BRINY"],
    is_rnav: false,
    notes: "FROM ZSE 15",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["rno"],
    arr_flows: ["rnon"],
    plane_classifications: [],
    route: ["..HARTT.EELZA"],
    is_rnav: true,
    notes: "FROM ZSE 13",
  },
];

export default loas;
