import { PLANE_CATEGORY, type loa } from "../types";

const loas: loa[] = [
  {
    dep_apts: ["fat"],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..PONDD..TAFTO..MUPTT.IRNMN"],
    is_rnav: true,
    notes: "AOB FL230",
  },
  {
    dep_apts: ["mry"],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..TOKIO.HUULL"],
    is_rnav: true,
    notes: "AOB FL230",
  },
  {
    dep_apts: ["mry"],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..LIBBO..CLMNS..MQO.VTU.SADDE"],
    is_rnav: false,
    notes: "AOB FL230",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: ["laxw"],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..IRNMN"],
    is_rnav: true,
    notes: "Direct no further than DOUIT",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: ["laxw"],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..AVE.SADDE"],
    is_rnav: false,
    notes: "Direct no further than DOUIT",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: ["laxe"],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..ZUUMA"],
    is_rnav: true,
    notes: "Direct no further than DOUIT",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lax"],
    arr_flows: ["laxe"],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..AVE.MOOR"],
    is_rnav: false,
    notes: "Direct no further than DOUIT",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["smo"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..EBAYE..BURGL..HONZK.BONJO"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["smo"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..BONJO"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["smo"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..FERN"],
    is_rnav: false,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lax", "smo"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.PROP],
    route: ["..WAYVE"],
    is_rnav: true,
    notes: "AOB FL230",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lax", "smo"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.PROP],
    route: ["..KIMMO"],
    is_rnav: false,
    notes: "AOB FL230",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..TILLT.BAUBB", "..RDHOT.PCIFC"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["OFFSH SXC", "COAST SXC"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: ["sfoe"],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["FLW.TANDY"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..TILLT.TILLT", "..RDHOT.OHSEA"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["OFFSH SXC", "COAST SXC"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: ["sfoe"],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["FLW.TANDY"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..EBAYE..BURGL..ELLBC.PCIFC"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["FLW.TANDY"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..EBAYE..BURGL..ELLBC.OHSEA"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["FLW.TANDY"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["rno", "smf"],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..REBRG.PCIFC"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: ["rno", "smf"],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..REBRG.OHSEA"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..PCFIC"],
    is_rnav: true,
    notes: "AOA FL240",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lgb"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..TANDY"],
    is_rnav: false,
    notes: "AOA FL240",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..OHSEA"],
    is_rnav: true,
    notes: "AOA FL240",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sna"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..TANDY"],
    is_rnav: false,
    notes: "AOA FL240",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["bur"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..EBAYE..BURGLE..HONZK.ROKKR"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["vny"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..EBAYE..BURGLE..HONZK.IVINS"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["bur"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..ROKKR"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["bur"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..FERN"],
    is_rnav: false,
    notes: "AOB FL310",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["vny"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..IVINS"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: ["sjc"],
    dep_flows: [],
    arr_apts: ["vny"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..FERN"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["bur", "vny"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.PROP],
    route: ["..WEESL"],
    is_rnav: true,
    notes: "AOB FL230",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sanw"],
    plane_classifications: [],
    route: ["MCKEY..LAX.COMIX", "YYUNG..LAX.COMIX"],
    is_rnav: true,
    notes: "Direct LAX approved",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: ["sfoe"],
    arr_apts: ["san"],
    arr_flows: ["sanw"],
    plane_classifications: [],
    route: ["CISKO..FLW..LAX.COMIX"],
    is_rnav: true,
    notes: "Direct LAX approved",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sanw"],
    plane_classifications: [],
    route: ["..LAX.HUBRD"],
    is_rnav: false,
    notes: "Direct LAX approved",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sanw"],
    plane_classifications: [],
    route: ["..LAX.COMIX", "..HUULK.COMIX"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sanw"],
    plane_classifications: [],
    route: ["..LAX.HUBRD"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sane"],
    plane_classifications: [],
    route: ["MCKEY..LAX.PLYYA", "YYUNG..LAX.PLYYA"],
    is_rnav: true,
    notes: "Direct LAX approved",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: ["sfoe"],
    arr_apts: ["san"],
    arr_flows: ["sane"],
    plane_classifications: [],
    route: ["CISKO..FLW..LAX.PLYYA"],
    is_rnav: true,
    notes: "Direct LAX approved",
  },
  {
    dep_apts: ["sfo", "oak"],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sane"],
    plane_classifications: [],
    route: ["..LAX.SHAMU"],
    is_rnav: false,
    notes: "Direct LAX approved",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sane"],
    plane_classifications: [],
    route: ["..LAX.PLYYA"],
    is_rnav: true,
    notes: "",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["san"],
    arr_flows: ["sane"],
    plane_classifications: [],
    route: ["..LAX.SHAMU"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["crq", "nfg"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..LEGOZ"],
    is_rnav: true,
    notes: "AOB FL250 via LANDO",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["crq", "nfg"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..AVE..FIM"],
    is_rnav: false,
    notes: "AOB FL250 via LANDO",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["psp", "trm", "udd"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..SIZLR"],
    is_rnav: true,
    notes: "AOB FL370",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["psp", "trm", "udd"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..PMD.V137.PSP"],
    is_rnav: false,
    notes: "AOB FL370",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["ont", "cno", "poc", "ajo", "emt", "ral", "sbd"],
    arr_flows: [],
    plane_classifications: [],
    route: ["ZIGGY"],
    is_rnav: true,
    notes: "AOB FL370",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["las"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["..TQILA.COKTL", ".Q174.FLCHR.COKTL"],
    is_rnav: true,
    notes: "AOB FL330; AOB FL310 via Q174",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["las"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.JET],
    route: ["J92.BTY.PUMLE"],
    is_rnav: false,
    notes: "AOB FL330",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["las"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.TURBOPROP, PLANE_CATEGORY.PROP],
    route: ["..FUULL.GAMES"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["las"],
    arr_flows: [],
    plane_classifications: [PLANE_CATEGORY.TURBOPROP, PLANE_CATEGORY.PROP],
    route: ["J92"],
    is_rnav: false,
    notes: "AOB FL290 via J92",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["hnd"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..FUULL.GAMES"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["hnd"],
    arr_flows: [],
    plane_classifications: [],
    route: ["J92"],
    is_rnav: false,
    notes: "AOB FL290 via J92",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["vgt"],
    arr_flows: [],
    plane_classifications: [],
    route: [".Q174.FLCHR.FLCHR"],
    is_rnav: true,
    notes: "AOB FL310",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["vgt"],
    arr_flows: [],
    plane_classifications: [],
    route: [".J92"],
    is_rnav: false,
    notes: "AOB FL290 via J92",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["lsv"],
    arr_flows: [],
    plane_classifications: [],
    route: [".J92"],
    is_rnav: false,
    notes: "AOB FL330",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sba"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..GVO..HABUT", "..SNS.J88.RZS"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sbp"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..MQO", "..CREPE"],
    is_rnav: false,
    notes: "",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["sbp"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..CADAB"],
    is_rnav: true,
    notes: "",
  },
];

export default loas;
