import { PLANE_CATEGORY, type loa } from "../types";

const loas: loa[] = [
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["slc"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..BVL", "..MLF"],
    is_rnav: true,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["slc"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..REO"],
    is_rnav: false,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["boi"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..NEERO", "..PRNCS"],
    is_rnav: true,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["boi"],
    arr_flows: [],
    plane_classifications: [],
    route: ["via filed route"],
    is_rnav: false,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["bil"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..YLSTN"],
    is_rnav: true,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["bil"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..BAM", "..REO..DBS"],
    is_rnav: false,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["gtf", "hln", "mso"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..REO"],
    is_rnav: false,
    notes: "From ZOA Area North/East",
  },
  {
    dep_apts: [],
    dep_flows: [],
    arr_apts: ["twf"],
    arr_flows: [],
    plane_classifications: [],
    route: ["..BAM..TWF"],
    is_rnav: false,
    notes: "From ZOA Area North/East",
  },
];

export default loas;
